# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 205364699e1af2810449304941f5b771f201d8bf3eb4d9bc8531ad7f7a336615e8c3075c88713eb9e8bece334f336b5311b15815ff5a4b9dc9ab85cee8af1c84

test:
  secret_key_base: ef82f3fa0f0f97ec390855ada3e42f824b09ec29b72a14fee11f0b5f85f724099016204ace9e0fc5ffb43abbe6832ddd5dca23ca17ac31497d7cfd45bd5333a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
